window.PLANT_DATA = {
    'seed': {
        id: 'seed',
        name: '種',
        cost: 10,
        range: 3.5,
        damage: 25,
        cooldown: 800,
        color: '#b8e0d2',
        description: '基本ユニット。時間と共に成長します。',
        effect: null,
        rarity: 'common'
    },
    'peashooter': {
        id: 'peashooter',
        name: 'ピーシューター',
        cost: 20,
        range: 4.0,
        damage: 30,
        cooldown: 800,
        color: '#52b788',
        description: '標準的な遠距離攻撃ユニット。',
        effect: null,
        rarity: 'common'
    },
    'rapid': {
        id: 'rapid',
        name: 'ガトリングピー',
        cost: 50,
        range: 3.5,
        damage: 15,
        cooldown: 250,
        color: '#40916c',
        description: '低威力だが非常に高速で連射します。',
        effect: null,
        rarity: 'rare'
    },
    'sniper': {
        id: 'sniper',
        name: 'スナイパー',
        cost: 40,
        range: 8.0,
        damage: 100,
        cooldown: 3000,
        color: '#2d6a4f',
        description: '超長射程・高威力ですが、攻撃は遅いです。',
        effect: null,
        rarity: 'rare'
    },
    'slow': {
        id: 'slow',
        name: 'アイスブルーム',
        cost: 30,
        range: 3.0,
        damage: 10,
        cooldown: 1000,
        color: '#74c69d',
        description: '敵を鈍足状態にします。',
        effect: 'slow',
        rarity: 'common'
    },
    'poison': {
        id: 'poison',
        name: 'ベノムシュルーム',
        cost: 45,
        range: 3.5,
        damage: 5,
        cooldown: 1000,
        color: '#9d0208',
        description: '継続ダメージを与える毒を付与します。',
        effect: 'poison',
        rarity: 'rare'
    },
    'splash': {
        id: 'splash',
        name: 'メロンパルト',
        cost: 60,
        range: 4.5,
        damage: 40,
        cooldown: 2000,
        color: '#e9c46a',
        description: '着弾地点の周囲に範囲ダメージを与えます。',
        effect: 'splash',
        rarity: 'rare'
    },
    'stun': {
        id: 'stun',
        name: 'ザップウィード',
        cost: 70,
        range: 3.0,
        damage: 20,
        cooldown: 2500,
        color: '#f4a261',
        description: '一定確率で敵をスタン（停止）させます。',
        effect: 'stun',
        rarity: 'epic'
    },
    'chain': {
        id: 'chain',
        name: 'ライトニングリード',
        cost: 80,
        range: 5.0,
        damage: 25,
        cooldown: 1200,
        color: '#e76f51',
        description: '近くの敵に攻撃が連鎖します。',
        effect: 'chain',
        rarity: 'epic'
    },
    'laser': {
        id: 'laser',
        name: 'レーザービーン',
        cost: 90,
        range: 6.0,
        damage: 15,
        cooldown: 100,
        color: '#00afb9',
        description: '直線のビームで継続ダメージを与えます。',
        effect: 'laser',
        rarity: 'epic'
    },
    'cannon': {
        id: 'cannon',
        name: 'ココナッツキャノン',
        cost: 100,
        range: 5.0,
        damage: 150,
        cooldown: 4000,
        color: '#6d597a',
        description: '広範囲に大爆発を起こします。',
        effect: 'splash_heavy',
        rarity: 'epic'
    },
    'mine': {
        id: 'mine',
        name: 'ポテトマイン',
        cost: 25,
        range: 1.0,
        damage: 500,
        cooldown: 20000,
        color: '#d4a373',
        description: '敵が踏むと大爆発します。',
        effect: 'mine',
        rarity: 'common'
    },
    'gold': {
        id: 'gold',
        name: 'ゴールデンブルーム',
        cost: 50,
        range: 0,
        damage: 0,
        cooldown: 5000,
        color: '#ffd700',
        description: '定期的にマナを生成します。',
        effect: 'income',
        rarity: 'rare'
    },
    'flame': {
        id: 'flame',
        name: 'ペッパーブレス',
        cost: 55,
        range: 2.5,
        damage: 40,
        cooldown: 500,
        color: '#d00000',
        description: '近距離に火炎放射を行います。',
        effect: 'burn',
        rarity: 'rare'
    },
    'wind': {
        id: 'wind',
        name: 'ハリケール',
        cost: 40,
        range: 4.0,
        damage: 5,
        cooldown: 2000,
        color: '#a8dadc',
        description: '敵を吹き飛ばして後退させます。',
        effect: 'pushback',
        rarity: 'rare'
    },
    'vampire': {
        id: 'vampire',
        name: 'ドラキュラオーキッド',
        cost: 65,
        range: 3.5,
        damage: 35,
        cooldown: 1000,
        color: '#4a0404',
        description: '敵を倒すとマナを回復します。',
        effect: 'leech',
        rarity: 'epic'
    },
    'executioner': {
        id: 'executioner',
        name: 'グリムローズ',
        cost: 120,
        range: 4.0,
        damage: 50,
        cooldown: 1500,
        color: '#212529',
        description: 'HPが30%以下の敵に3倍のダメージを与えます。',
        effect: 'execute',
        rarity: 'legendary'
    },
    'nuke': {
        id: 'nuke',
        name: 'ドゥームシュルーム',
        cost: 200,
        range: 3.0,
        damage: 1000,
        cooldown: 30000,
        color: '#343a40',
        description: '超広範囲に壊滅的なダメージを与えます。',
        effect: 'nuke',
        rarity: 'legendary'
    },
    'prism': {
        id: 'prism',
        name: 'プリズムグラス',
        cost: 150,
        range: 5.0,
        damage: 60,
        cooldown: 800,
        color: '#ff99c8',
        description: '3方向に攻撃を分散させます。',
        effect: 'multi_shot',
        rarity: 'legendary'
    },
    'time': {
        id: 'time',
        name: 'タイムワープ',
        cost: 180,
        range: 4.0,
        damage: 0,
        cooldown: 5000,
        color: '#0077b6',
        description: '範囲内の敵の時間を一時的に止めます。',
        effect: 'freeze',
        rarity: 'legendary'
    }
};

window.PLANT_RARITY_WEIGHTS = {
    'common': 60,
    'rare': 30,
    'epic': 9,
    'legendary': 1
};
